config/routes.rb
Rails.application.routes.draw do
devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  #検索機能
  get 'search' => 'searchs#search'
  #フォロー機能
  resources :users do
    resource :relationships, only: [:create, :destroy]#今回は作成と解除のみ
    get :following, on: :member#フォローしてる人の表示
    get :followers, on: :member#フォローしてる人の表示
  end

  resources :books do
  resource :favorites, only: [:create, :destroy]#いいね
  resources :book_comments, only: [:create, :destroy]#コメント


  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController


  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.create(book_id: params[:book_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favo.html.erb
<% if current_user.already_favorited?(book) %><!--←すでにｲﾈ!!をしているか否か-->
 <%= link_to book_favorites_path(book), method: :delete do %>
  <i class="fas fa-heart"></i><!--ハートマークの追加-->
 <% end %>
  <%= book.favorites.count %><!--bookの評価をカウントする-->
 <% else %>
  <%= link_to book_favorites_path(book), method: :post do %>
   <i class="far fa-heart"></i>
  <% end %>
   <%= book.favorites.count %>
  <% end %>

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %><!--ユーザーがログインしているか-->
<!--以下favo-->
<% if current_user.already_favorited?(book) %>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      <i class="fas fa-heart"></i>
    <% end %>
      <%= book.favorites.count %>
    <% else %>
      <%= link_to book_favorites_path(book), method: :post, remote: true do %>
      <i class="far fa-heart"></i>
    <% end %>
    <%= book.favorites.count %>
    <% end %>
<% end %>