config/routes.rb
Rails.application.routes.draw do
devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  #検索機能
  get 'search' => 'searchs#search'
  #フォロー機能
  resources :users do
    resource :relationships, only: [:create, :destroy]#今回は作成と解除のみ
    get :following, on: :member#フォローしてる人の表示
    get :followers, on: :member#フォローしてる人の表示
  end

  resources :books do
  resource :favorites, only: [:create, :destroy]#いいね
  resources :book_comments, only: [:create, :destroy]#コメント


  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction,length: { maximum: 50}

  has_many :favorites, dependent: :destroy#いいね機能


  # コメント機能
  has_many :book_comments, dependent: :destroy

  #以下follower機能
  #フォローする側
  has_many :relationships, foreign_key: :following_id
  #フォローしている人全員を持ってくる
  has_many :followings, through: :relationships, source: :follower


  #フォローされる側
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
  #フォローしてくれている人を全部持ってくる
  has_many :followers, through: :reverse_of_relationships, source: :following

  def already_favorited?(book)
      self.favorites.exists?(book_id: book.id)
  end

  def already_following?(user)
      self.followings.exists?(id: user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: @user.id)
    @booknew = Book.new
  end

  def index
    @users = User.all
    #@userfollow = User.where.not(id: current_user.id)
    @booknew = Book.new
    @user = current_user
  end

  #フォロワー機能
  def following
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end


  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
        <!--フォロー機能-->
        <td>
        <%= link_to user.followings.count, following_user_path(user) %> フォロー
        <%= link_to user.followers.count, followers_user_path(user) %>フォロワー
        </td>
        <td>
          <% if current_user.already_following?(user) %>
          <%= link_to user_relationships_path(user), method: :delete do %>
          <button class="btn btn-danger">フォロー解除</button>
          <% end %>
          <% else %>
          <%= link_to user_relationships_path(user), method: :post do %>
          <button class="btn btn-primary">フォロー</button>
          <% end %>
          <% end %>
        </td>
        </tr>
          <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
	</tr>
	<tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
	</tr>

  <!--↓ログインしているユーザーが本人ではない場合-->
  <% unless current_user == user %>
        <% if current_user.already_following?(user) %>
          <th><%= link_to user_relationships_path(user), method: :delete do %>
            <button class="btn btn-danger">フォロー解除</button>
          </th>
          <% end %>
          <% else %>
          <th><%= link_to user_relationships_path(user), method: :post do %>
            <button class="btn btn-primary">フォロー</button>
          </th>
          <% end %>
        <% end %>
    <% end %>
  <!--以上追加部分-->
</table>

  <div class='row'>
    <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
  </div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container marketing">
  <div class "row d-flex justyfy-content-center">
    <div class="col-10 mt-5">
      <h1>FOLLOWERS</h1>
      <table class="table text-center">
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
        <!--フォロー機能-->
        <td>
        <%= link_to user.followings.count, following_user_path(user) %> フォロー
        <%= link_to user.followers.count, followers_user_path(user) %>フォロワー
        </tb>
        <td>
          <% if current_user.already_following?(user) %>
          <%= link_to user_relationships_path(user), method: :delete do %>
          <button class="btn btn-danger">フォロー解除</button>
          <% end %>
          <% else %>
          <%= link_to user_relationships_path(user), method: :post do %>
          <button class="btn btn-primary">フォロー</button>
          <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/following.html.erb
<div class="container marketing">
  <div class "row d-flex justyfy-content-center">
    <div class="col-10 mt-5">
      <h1>FOLLOWING</h1>
      <table class="table text-center">
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
        <!--フォロー機能-->
        <td>
        <%= link_to user.followings.count, following_user_path(user) %> フォロー
        <%= link_to user.followers.count, followers_user_path(user) %>フォロワー
        </td>
        <td>
          <% if current_user.already_following?(user) %>
          <%= link_to user_relationships_path(user), method: :delete do %>
          <button class="btn btn-danger">フォロー解除</button>
          <% end %>
          <% else %>
          <%= link_to user_relationships_path(user), method: :post do %>
          <button class="btn btn-primary">フォロー</button>
          <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
        <h2>User info</h2>
        <%= render 'info', user: @user %>
        <h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @booknew %>
        </div>
    <div class='col-md-8 offset-md-1'>
        <h2>Users</h2>
        <%= render 'users/index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @booknew %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>