config/routes.rb
Rails.application.routes.draw do
devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  #検索機能
  get 'search' => 'searchs#search'
  #フォロー機能
  resources :users do
    resource :relationships, only: [:create, :destroy]#今回は作成と解除のみ
    get :following, on: :member#フォローしてる人の表示
    get :followers, on: :member#フォローしてる人の表示
  end

  resources :books do
  resource :favorites, only: [:create, :destroy]#いいね
  resources :book_comments, only: [:create, :destroy]#コメント


  end
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true, length: { in: 1..200}
	#いいね
	 has_many :favorites, dependent: :destroy
	 #コメント機能
	 has_many :book_comments, dependent: :destroy

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :editing_user, only: [:edit]

    def show
    @booknew = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    # @user = User.find(@book.user_id)
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def index
    @booknew = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @booknew = Book.new(book_params)
    @booknew.user_id = current_user.id
    if @booknew.save
      redirect_to book_path(@booknew.id), notice: "You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params[:book].permit(:title,:body)
  end

  def editing_user
    book = Book.find(params[:id])
    if book.user != current_user
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
<td><%= form_with model:[@book, @book_comment], local:true do |f| %>
            <%= f.text_area :comment, size: "40x5" %>
            <%= f.submit '送信' %>
            <% end %>
            </td>
            <table>
          <thead>
            <tr>
              <th>コメント投稿者</th>
              <th>コメント内容</th>
            </tr>
          </thead>
          <tbody>
            <% @book.book_comments.each do |book_comment| %>
              <tr>
                <td><%= link_to user_path(book_comment.user) do %>
                  <%= attachment_image_tag book_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg" %>
                  <%= book_comment.user.name  %>
                  <% end %>
                </td>
                <td><%= book_comment.comment %></td>
                <% if book_comment.user_id == current_user.id %>
                <td><%= link_to "削除", book_book_comment_path(book_comment.book_id, book_comment.id), method: :delete %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>

app/views/books/_error.html.erb
<p id="notice"></p>
    <% if model.errors.any? %>
  <div id="error_explanation">
    <h3 class="text-danger"><%= pluralize(model.errors.count,"error") %> prohibited this product from being saved:</h3>

  <ul><% model.errors.full_messages.each do |message| %>
    <li class="text-danger"><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <!--いいね・コメント機能-->
        <td><%= render 'favorites/favo', book: book %></td>
        <td><%= link_to "コメント：#{book.book_comments.count}", book_path(book.id) %></td>
        <tb><</tb>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @booknew %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @booknew %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>

    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @booknew %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@user) do %>
            <%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= link_to @user.name, user_path(@user) %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <!--いいねのアクションを実装 -->
          <td><%= render 'favorites/favo', book: @book %></td>  <!--いいね機能-->
          <td><%= link_to "コメント数:#{@book.book_comments.count}", book_path(@book.id) %></td>
          <% if @book.user_id == current_user.id %>
          <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
          <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
      </table>
          <%= render 'books/comment', book: @book, book_comment: @book_comment %>
    </div>
  </div>
</div>